version: "3"
services:
    postgres:
        container_name: postgres
        image: postgres
        restart: always
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - postgres_backup:/backup
        networks:
            - postgres
        environment:
            - POSTGRES_PASSWORD=postgres
        ports:
            - "5432:5432"
volumes:
    postgres_data:
        external: true
    postgres_backup:
        external: true

networks:
    default:
        driver: bridge

