version: "3"
services:
    postgres:
        container_name: postgres
        image: postgres
        restart: always
        volumes:
            - pgdata:/var/lib/postgresql/data
            - pgbackup:/backup
        environment:
            - POSTGRES_PASSWORD=postgres
        ports:
            - "5432:5432"
volumes:
    pgdata:
    pgbackup:
