version: "3.5"

services:
  redis:
    image: redis
    command: redis-server --requirepass Cjrjkjdcrbq_555
    restart: always
    hostname: redis-db
    container_name: redis-db
    env_file: docker-compose.env
    volumes:
      - "redis_data:/data"
    ports:
      - "6379:6379"

volumes:
  redis_data:
    external: true

networks:
  redis-db:
    external: true
